### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by retiolus** [aliraeisdanaei/NetflixMovieSuggester#1]
```
****Netflix Movie Suggester****
***********Main Menu***********

Current User Name:  default 

(1) Suggest Movie
(2) Change Users
(3) View & Change Preferances
(4) Create New User
(5) About
(6) Quit
Enter Option: 1
Traceback (most recent call last):
  File "movieSuggester.py", line 356, in <module>
    showMainMenu()
  File "movieSuggester.py", line 333, in showMainMenu
    giveMovie()
  File "movieSuggester.py", line 18, in giveMovie
    movie = scraper.findNextMovie(crntUser)
  File "/home/kaonashi696/Documents/bots/GiveMeAnIdea/NetflixMovieSuggester/netflixWebScraper.py", line 30, in findNextMovie
    movie = WebScraper.getMovieFromCode(self.__movieList.pop())
  File "/home/kaonashi696/Documents/bots/GiveMeAnIdea/NetflixMovieSuggester/netflixWebScraper.py", line 52, in getMovieFromCode
    rlsyr = int(movieCode.find(
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by aliraeisdanaei** [comment]
Hello oh retiolus, 

Thank thee for bringing this to my attention. I am actually really glad to have received this. It is a sign that someone out there used my code. :)
Turns out that the website had changed their inner html stuff, so I was hitting a wall in getting some of the information. 

And sadly, 
they depricated the link to the Netflix website, so I also changed the link to a wikipedia article about the number 404. 

If you are savy and have the vigour of a feisty one, you can find a better solution to my bandaid work. 

Thanks & God bless, 
Ali Raeisdanaei
